apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    method: from-code
  name: nginx-yaml-p001
spec:
  containers:
  - image: nginx
    name: nginx-yaml-c001
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
